# Generated by Django 5.0.7 on 2024-09-22 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
