# Generated by Django 5.0.7 on 2024-09-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
