# Generated by Django 5.0.7 on 2024-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_manager_id_employee_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
