# Generated by Django 5.0.7 on 2024-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_balance',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
