# Generated by Django 5.0.7 on 2024-09-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0002_vacation_balance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation_balance',
            name='is_accepted',
        ),
    ]
