# Generated by Django 5.0.7 on 2024-09-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0003_remove_vacation_balance_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_balance',
            name='reason',
            field=models.TextField(default='I hope this message finds you well.After carefully reviewing your leave request, I regret to inform you that, due to current circumstances, we are unable to approve your time off at this time.We understand the importance of time away and encourage you to discuss alternative dates for your leave. Please let me know if there is another time that would work for you, and I’ll do my best to accommodate it.Thank you for your understanding. Should you have any questions or concerns, feel free to reach out.', max_length=2000),
        ),
    ]
