# Generated by Django 5.0.7 on 2024-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0004_vacation_balance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_balance',
            name='reason',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
