# Generated by Django 5.0.7 on 2024-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0005_alter_vacation_balance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_balance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=200, null=True),
        ),
    ]
