# Generated by Django 5.0.7 on 2024-09-24 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacationBook', '0006_alter_vacation_balance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacation_Balance',
            new_name='LeaveRequest',
        ),
    ]
